---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/gitleaks/gitleaks
    rev: 83d9cd684c87d95d656c1458ef04895a7f1cbd8e  # frozen: v8.30.1
    hooks:
      - id: gitleaks

  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: 9257c6050c0261b8c57e712f632dc4a8010109a9  # frozen: v1.25.2
    hooks:
      - id: zizmor

  - repo: https://github.com/terraform-docs/terraform-docs
    rev: b8f73e22eae2560d55ec5e9da62251c068fa9ccb  # frozen: v0.23.0
    hooks:
      - id: terraform-docs-system
        args: ["."]
        pass_filenames: false

  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: 36064fa396bcbcd7df169b9f932536b7e6d2666c  # frozen: v8.4.0
    hooks:
      - id: cspell # Spell check changed files
        args:
          # - --config cspell.json
          - --no-progress

exclude: .devcontainer/devcontainer-lock.json
