---
formatter: markdown table

recursive:
  enabled: true
  path: modules
  include-main: false

content: |-
  <!-- markdownlint-disable -->
  <!-- prettier-ignore-start -->
  {{ .Content }}
  <!-- prettier-ignore-end -->
  <!-- markdownlint-enable -->

output:
  file: "README.md"
  mode: inject

settings:
  lockfile: false
