# yamllint disable-file
---
name: OpenSSF Scorecard

on:
  push:
    branches:
      - main
  schedule:
    - cron: "30 6 * * 1"

permissions: {}

jobs:
  openssf-scorecard:
    name: OpenSSF Scorecard
    permissions:
      contents: read
      id-token: write
      security-events: write
    uses: ministryofjustice/data-platform-github-actions/.github/workflows/openssf-scorecard.yml@260d708201e0beaa345f00a87462310da26b34ae # v3.5.0
