---
name: Spell Check

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  spell-check:
    name: Spell Check
    permissions:
      contents: read
    uses: ministryofjustice/data-platform-github-actions/.github/workflows/spell-check.yml@ad85a30531b1adaa06bc6e9daed95d9930f28687 # v3.4.2
