# yamllint disable-file
---
name: Spell Check

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  spell-check:
    name: Spell Check
    permissions:
      contents: read
    uses: ministryofjustice/data-platform-github-actions/.github/workflows/spell-check.yml@5d8d0f00346daa26a7dd1283ecd098bbcd2b5396 # v4.1.1
