# yamllint disable-file
---
name: Super Linter

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  super-linter:
    name: Super Linter
    permissions:
      contents: read
      packages: read
      statuses: write
    uses: ministryofjustice/data-platform-github-actions/.github/workflows/super-linter.yml@260d708201e0beaa345f00a87462310da26b34ae # v3.5.0
